services:
  organiclever-be:
    environment:
      ORGANICLEVER_BE_PORT: "8202"
      ORGANICLEVER_BE_CORS_ORIGINS: "*"

  organiclever-app-web:
    environment:
      ORGANICLEVER_BE_URL: "http://organiclever-be:8202"
