FROM golang:1.26-alpine

RUN apk add --no-cache git gcc musl-dev

WORKDIR /app

# Copy go workspace files
COPY go.work go.work.sum ./
COPY apps/ayokoding-cli/go.mod apps/ayokoding-cli/go.sum apps/ayokoding-cli/
COPY libs/golang-commons/go.mod libs/golang-commons/go.sum libs/golang-commons/
COPY libs/hugo-commons/go.mod libs/hugo-commons/go.sum libs/hugo-commons/

WORKDIR /app/apps/ayokoding-cli
RUN go mod download
WORKDIR /app

COPY . .

WORKDIR /app/apps/ayokoding-cli
